name: Create Module Release

on: 
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # get the version number from the tag
    - name: Extract tag version number
      id: get_version
      uses: battila7/get-version-action@v2

    # replace links in the manifest with the versioned ones
    - name: Substitute Manifest and Download Links For Versioned Ones
      id: sub_manifest
      uses: microsoft/variable-substitution@v1
      with:
        files: 'src/module.json'
      env:
        version: ${{steps.get_version.outputs.version-without-v}}
        url: https://github.com/${{github.repository}}
        manifest: https://github.com/${{github.repository}}/releases/latest/download/module.json
        download: https://github.com/${{github.repository}}/releases/download/${{github.event.release.tag_name}}/module.zip
        bugs: https://github.com/${{github.repository}}/issues

    - name: Create Zip File
      working-directory: src
      run: zip -r ./module.zip module.json assets/ scripts/

    # Create release
    - name: Create Release
      id: create_version_release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true # Set this to false if you want to prevent updating existing releases
        name: ${{ github.event.release.name }}
        prerelease: ${{ github.event.release.prerelease }}
        artifacts: 'src/module.json, src/module.zip'
        tag: ${{ github.event.release.tag_name }}
        body: ${{ github.event.release.body }}